### ISSUE TITLE
扫描不出文件

### ISSUE THREAD

**Issue by RikkaBlue** [CberYellowstone/DanDanPlay-PHP#1]
克隆下仓库后直接部署，没办法扫描出文件

执行 `php do.php`
```
PHP Notice:  Undefined index: action in /var/www/DandanPlay/function.php on line 453
PHP Notice:  Undefined index: action in /var/www/DandanPlay/function.php on line 456
PHP Notice:  Undefined index: action in /var/www/DandanPlay/function.php on line 459
PHP Notice:  Undefined index: action in /var/www/DandanPlay/function.php on line 462
PHP Notice:  Undefined index: action in /var/www/DandanPlay/function.php on line 465
PHP Notice:  Undefined index: action in /var/www/DandanPlay/function.php on line 468
PHP Notice:  Undefined index: action in /var/www/DandanPlay/function.php on line 471
PHP Notice:  Undefined index: animeName in /var/www/DandanPlay/function.php on line 83
PHP Notice:  Undefined index: animeName in /var/www/DandanPlay/function.php on line 83
PHP Notice:  Undefined index: animeName in /var/www/DandanPlay/function.php on line 83
```

video 下面是一个挂载的 samba 硬盘的软链接。
```
[Lilith-Raws] Enen no Shouboutai S02 - 15 [BiliBili][WEB-DL][1080p][AVC AAC][CHT][MKV].mkv
```
都是类似这样的文件  

简单的 nginx 配置
```conf
server {
        listen 80;
        server_name ab.bb;
        index   index.php;
        root    /var/www/DandanPlay;

        location / {
            try_files $uri $uri/ =404;
      }

        location ~ \.php$ {
           include snippets/fastcgi-php.conf;
           fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
      }
}
```
![image](https://user-images.githubusercontent.com/46104879/97113241-f8c6bb80-1723-11eb-98c4-aeb2b764b5ca.png)

**Comment by CberYellowstone** [comment]
> 克隆下仓库后直接部署，没办法扫描出文件
> 
> 执行 `php do.php`
> 
> ```
> PHP Notice:  Undefined index: action in /var/www/DandanPlay/function.php on line 453
> PHP Notice:  Undefined index: action in /var/www/DandanPlay/function.php on line 456
> PHP Notice:  Undefined index: action in /var/www/DandanPlay/function.php on line 459
> PHP Notice:  Undefined index: action in /var/www/DandanPlay/function.php on line 462
> PHP Notice:  Undefined index: action in /var/www/DandanPlay/function.php on line 465
> PHP Notice:  Undefined index: action in /var/www/DandanPlay/function.php on line 468
> PHP Notice:  Undefined index: action in /var/www/DandanPlay/function.php on line 471
> PHP Notice:  Undefined index: animeName in /var/www/DandanPlay/function.php on line 83
> PHP Notice:  Undefined index: animeName in /var/www/DandanPlay/function.php on line 83
> PHP Notice:  Undefined index: animeName in /var/www/DandanPlay/function.php on line 83
> ```
> 
> video 下面是一个挂载的 samba 硬盘的软链接。
> 
> ```
> [Lilith-Raws] Enen no Shouboutai S02 - 15 [BiliBili][WEB-DL][1080p][AVC AAC][CHT][MKV].mkv
> ```
> 
> 都是类似这样的文件
> 
> 简单的 nginx 配置
> 
> ```
> server {
>         listen 80;
>         server_name ab.bb;
>         index   index.php;
>         root    /var/www/DandanPlay;
> 
>         location / {
>             try_files $uri $uri/ =404;
>       }
> 
>         location ~ \.php$ {
>            include snippets/fastcgi-php.conf;
>            fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
>       }
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/46104879/97113241-f8c6bb80-1723-11eb-98c4-aeb2b764b5ca.png)

检查一下目录有无读写权限，本地777权限即可，我没有在nginx上部署过，之后会去测试一下

**Comment by CberYellowstone** [comment]
另外，video目录下的目录结构应改为./video / 番剧名(标准中文译名) / 视频文件(多个)
